[package]
name = "remote_printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "windows")'.dependencies]
camellia_remote_protocol = { package = "camellia-remote-protocol", version = "0.1.0", path = "../camellia_remote_protocol" }
winapi = { version = "0.3" }
windows-strings = "0.3.1"
