import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { protoSourceDigest, protoSources } from './proto-sources.mjs';

const toolsDir = dirname(fileURLToPath(import.meta.url));
const output = resolve(toolsDir, '../src/proto/generated.js');
const filter = resolve(toolsDir, 'proto-filter.json');
const temporaryDir = await mkdtemp(join(tmpdir(), 'camellia-proto-'));
const temporaryOutput = join(temporaryDir, 'generated.js');
const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx';

try {
  const result = spawnSync(
    npx,
    [
      '--yes',
      '--package=protobufjs-cli@2.6.1',
      'pbjs',
      '-t',
      'static-module',
      '-w',
      'esm',
      '--filter',
      filter,
      '--no-verify',
      '--no-delimited',
      '--no-typeurl',
      '--no-service',
      '--no-comments',
      '--no-create',
      '-o',
      temporaryOutput,
      ...protoSources
    ],
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }
  );
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    throw new Error(result.stderr.trim() || `pbjs exited with status ${result.status}`);
  }

  const digest = await protoSourceDigest();
  const generated = await readFile(temporaryOutput, 'utf8');
  const header = [
    '// Generated by `npm run generate:proto`; do not edit.',
    `// camellia-proto-source-sha256: ${digest}`,
    ''
  ].join('\n');
  await writeFile(output, `${header}${generated}`);
  process.stdout.write(`Generated ${output}\n`);
} finally {
  await rm(temporaryDir, { force: true, recursive: true });
}
