// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'flutter_ffi.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `initialize`, `load_recent_peers`, `main_broadcast_message`, `set_cur_session_id_`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TEXTURE_RENDER_KEY`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Stream<String> startGlobalEventStream({required String appType}) => RustLib
    .instance
    .api
    .crateFlutterFfiStartGlobalEventStream(appType: appType);

Future<void> stopGlobalEventStream({required String appType}) =>
    RustLib.instance.api.crateFlutterFfiStopGlobalEventStream(appType: appType);

Future<void> hostStopSystemKeyPropagate({required bool stopped}) => RustLib
    .instance
    .api
    .crateFlutterFfiHostStopSystemKeyPropagate(stopped: stopped);

int peerGetSessionsCount({required String id, required int connType}) => RustLib
    .instance
    .api
    .crateFlutterFfiPeerGetSessionsCount(id: id, connType: connType);

String sessionAddExistedSync({
  required String id,
  required UuidValue sessionId,
  required List<int> displays,
  required bool isViewCamera,
}) => RustLib.instance.api.crateFlutterFfiSessionAddExistedSync(
  id: id,
  sessionId: sessionId,
  displays: displays,
  isViewCamera: isViewCamera,
);

String sessionAddSync({
  required UuidValue sessionId,
  required String id,
  required bool isFileTransfer,
  required bool isViewCamera,
  required bool isPortForward,
  required bool isRdp,
  required bool isTerminal,
  required String switchUuid,
  required bool forceRelay,
  required String password,
  required bool isSharedPassword,
  String? connToken,
}) => RustLib.instance.api.crateFlutterFfiSessionAddSync(
  sessionId: sessionId,
  id: id,
  isFileTransfer: isFileTransfer,
  isViewCamera: isViewCamera,
  isPortForward: isPortForward,
  isRdp: isRdp,
  isTerminal: isTerminal,
  switchUuid: switchUuid,
  forceRelay: forceRelay,
  password: password,
  isSharedPassword: isSharedPassword,
  connToken: connToken,
);

Stream<EventToUI> sessionStart({
  required UuidValue sessionId,
  required String id,
}) => RustLib.instance.api.crateFlutterFfiSessionStart(
  sessionId: sessionId,
  id: id,
);

Stream<EventToUI> sessionStartWithDisplays({
  required UuidValue sessionId,
  required String id,
  required List<int> displays,
}) => RustLib.instance.api.crateFlutterFfiSessionStartWithDisplays(
  sessionId: sessionId,
  id: id,
  displays: displays,
);

Future<bool?> sessionGetRemember({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetRemember(sessionId: sessionId);

Future<bool?> sessionGetToggleOption({
  required UuidValue sessionId,
  required String arg,
}) => RustLib.instance.api.crateFlutterFfiSessionGetToggleOption(
  sessionId: sessionId,
  arg: arg,
);

bool sessionGetToggleOptionSync({
  required UuidValue sessionId,
  required String arg,
}) => RustLib.instance.api.crateFlutterFfiSessionGetToggleOptionSync(
  sessionId: sessionId,
  arg: arg,
);

Future<String?> sessionGetOption({
  required UuidValue sessionId,
  required String arg,
}) => RustLib.instance.api.crateFlutterFfiSessionGetOption(
  sessionId: sessionId,
  arg: arg,
);

Future<void> sessionLogin({
  required UuidValue sessionId,
  required String osUsername,
  required String osPassword,
  required String password,
  required bool remember,
}) => RustLib.instance.api.crateFlutterFfiSessionLogin(
  sessionId: sessionId,
  osUsername: osUsername,
  osPassword: osPassword,
  password: password,
  remember: remember,
);

Future<void> sessionSend2Fa({
  required UuidValue sessionId,
  required String code,
  required bool trustThisDevice,
}) => RustLib.instance.api.crateFlutterFfiSessionSend2Fa(
  sessionId: sessionId,
  code: code,
  trustThisDevice: trustThisDevice,
);

bool sessionGetEnableTrustedDevices({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetEnableTrustedDevices(sessionId: sessionId);

bool willSessionCloseCloseSession({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiWillSessionCloseCloseSession(sessionId: sessionId);

Future<void> sessionClose({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionClose(sessionId: sessionId);

Future<void> sessionRefresh({
  required UuidValue sessionId,
  required int display,
}) => RustLib.instance.api.crateFlutterFfiSessionRefresh(
  sessionId: sessionId,
  display: display,
);

Future<void> sessionTakeScreenshot({
  required UuidValue sessionId,
  required int display,
}) => RustLib.instance.api.crateFlutterFfiSessionTakeScreenshot(
  sessionId: sessionId,
  display: display,
);

Future<String> sessionHandleScreenshot({
  required UuidValue sessionId,
  required String action,
}) => RustLib.instance.api.crateFlutterFfiSessionHandleScreenshot(
  sessionId: sessionId,
  action: action,
);

bool sessionIsMultiUiSession({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionIsMultiUiSession(sessionId: sessionId);

Future<void> sessionRecordScreen({
  required UuidValue sessionId,
  required bool start,
}) => RustLib.instance.api.crateFlutterFfiSessionRecordScreen(
  sessionId: sessionId,
  start: start,
);

bool sessionGetIsRecording({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetIsRecording(sessionId: sessionId);

Future<void> sessionReconnect({
  required UuidValue sessionId,
  required bool forceRelay,
}) => RustLib.instance.api.crateFlutterFfiSessionReconnect(
  sessionId: sessionId,
  forceRelay: forceRelay,
);

Future<void> sessionToggleOption({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionToggleOption(
  sessionId: sessionId,
  value: value,
);

Future<void> sessionTogglePrivacyMode({
  required UuidValue sessionId,
  required String implKey,
  required bool on_,
}) => RustLib.instance.api.crateFlutterFfiSessionTogglePrivacyMode(
  sessionId: sessionId,
  implKey: implKey,
  on_: on_,
);

Future<String?> sessionGetFlutterOption({
  required UuidValue sessionId,
  required String k,
}) => RustLib.instance.api.crateFlutterFfiSessionGetFlutterOption(
  sessionId: sessionId,
  k: k,
);

Future<void> sessionSetFlutterOption({
  required UuidValue sessionId,
  required String k,
  required String v,
}) => RustLib.instance.api.crateFlutterFfiSessionSetFlutterOption(
  sessionId: sessionId,
  k: k,
  v: v,
);

int getNextTextureKey() =>
    RustLib.instance.api.crateFlutterFfiGetNextTextureKey();

String getLocalFlutterOption({required String k}) =>
    RustLib.instance.api.crateFlutterFfiGetLocalFlutterOption(k: k);

Future<void> setLocalFlutterOption({required String k, required String v}) =>
    RustLib.instance.api.crateFlutterFfiSetLocalFlutterOption(k: k, v: v);

String getLocalKbLayoutType() =>
    RustLib.instance.api.crateFlutterFfiGetLocalKbLayoutType();

Future<void> setLocalKbLayoutType({required String kbLayoutType}) => RustLib
    .instance
    .api
    .crateFlutterFfiSetLocalKbLayoutType(kbLayoutType: kbLayoutType);

Future<String?> sessionGetViewStyle({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetViewStyle(sessionId: sessionId);

Future<void> sessionSetViewStyle({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetViewStyle(
  sessionId: sessionId,
  value: value,
);

Future<String?> sessionGetScrollStyle({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetScrollStyle(sessionId: sessionId);

Future<void> sessionSetScrollStyle({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetScrollStyle(
  sessionId: sessionId,
  value: value,
);

Future<int?> sessionGetEdgeScrollEdgeThickness({
  required UuidValue sessionId,
}) => RustLib.instance.api.crateFlutterFfiSessionGetEdgeScrollEdgeThickness(
  sessionId: sessionId,
);

Future<void> sessionSetEdgeScrollEdgeThickness({
  required UuidValue sessionId,
  required int value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetEdgeScrollEdgeThickness(
  sessionId: sessionId,
  value: value,
);

Future<String?> sessionGetImageQuality({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionGetImageQuality(
      sessionId: sessionId,
    );

Future<void> sessionSetImageQuality({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetImageQuality(
  sessionId: sessionId,
  value: value,
);

Future<String?> sessionGetKeyboardMode({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionGetKeyboardMode(
      sessionId: sessionId,
    );

Future<void> sessionSetKeyboardMode({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetKeyboardMode(
  sessionId: sessionId,
  value: value,
);

String? sessionGetReverseMouseWheelSync({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionGetReverseMouseWheelSync(
      sessionId: sessionId,
    );

Future<void> sessionSetReverseMouseWheel({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetReverseMouseWheel(
  sessionId: sessionId,
  value: value,
);

String? sessionGetDisplaysAsIndividualWindows({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionGetDisplaysAsIndividualWindows(
      sessionId: sessionId,
    );

Future<void> sessionSetDisplaysAsIndividualWindows({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetDisplaysAsIndividualWindows(
  sessionId: sessionId,
  value: value,
);

String? sessionGetUseAllMyDisplaysForTheRemoteSession({
  required UuidValue sessionId,
}) => RustLib.instance.api
    .crateFlutterFfiSessionGetUseAllMyDisplaysForTheRemoteSession(
      sessionId: sessionId,
    );

Future<void> sessionSetUseAllMyDisplaysForTheRemoteSession({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api
    .crateFlutterFfiSessionSetUseAllMyDisplaysForTheRemoteSession(
      sessionId: sessionId,
      value: value,
    );

Future<Int32List?> sessionGetCustomImageQuality({
  required UuidValue sessionId,
}) => RustLib.instance.api.crateFlutterFfiSessionGetCustomImageQuality(
  sessionId: sessionId,
);

bool sessionIsKeyboardModeSupported({
  required UuidValue sessionId,
  required String mode,
}) => RustLib.instance.api.crateFlutterFfiSessionIsKeyboardModeSupported(
  sessionId: sessionId,
  mode: mode,
);

Future<void> sessionSetCustomImageQuality({
  required UuidValue sessionId,
  required int value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetCustomImageQuality(
  sessionId: sessionId,
  value: value,
);

Future<void> sessionSetCustomFps({
  required UuidValue sessionId,
  required int fps,
}) => RustLib.instance.api.crateFlutterFfiSessionSetCustomFps(
  sessionId: sessionId,
  fps: fps,
);

Future<int?> sessionGetTrackpadSpeed({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetTrackpadSpeed(sessionId: sessionId);

Future<void> sessionSetTrackpadSpeed({
  required UuidValue sessionId,
  required int value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetTrackpadSpeed(
  sessionId: sessionId,
  value: value,
);

Future<void> sessionLockScreen({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionLockScreen(sessionId: sessionId);

Future<void> sessionCtrlAltDel({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionCtrlAltDel(sessionId: sessionId);

Future<void> sessionSwitchDisplay({
  required bool isDesktop,
  required UuidValue sessionId,
  required List<int> value,
}) => RustLib.instance.api.crateFlutterFfiSessionSwitchDisplay(
  isDesktop: isDesktop,
  sessionId: sessionId,
  value: value,
);

Future<void> sessionHandleFlutterKeyEvent({
  required UuidValue sessionId,
  required String character,
  required int usbHid,
  required int lockModes,
  required bool downOrUp,
}) => RustLib.instance.api.crateFlutterFfiSessionHandleFlutterKeyEvent(
  sessionId: sessionId,
  character: character,
  usbHid: usbHid,
  lockModes: lockModes,
  downOrUp: downOrUp,
);

Future<void> sessionHandleFlutterRawKeyEvent({
  required UuidValue sessionId,
  required String name,
  required int platformCode,
  required int positionCode,
  required int lockModes,
  required bool downOrUp,
}) => RustLib.instance.api.crateFlutterFfiSessionHandleFlutterRawKeyEvent(
  sessionId: sessionId,
  name: name,
  platformCode: platformCode,
  positionCode: positionCode,
  lockModes: lockModes,
  downOrUp: downOrUp,
);

void sessionEnterOrLeave({required UuidValue sessionId, required bool enter}) =>
    RustLib.instance.api.crateFlutterFfiSessionEnterOrLeave(
      sessionId: sessionId,
      enter: enter,
    );

Future<void> sessionInputKey({
  required UuidValue sessionId,
  required String name,
  required bool down,
  required bool press,
  required bool alt,
  required bool ctrl,
  required bool shift,
  required bool command,
}) => RustLib.instance.api.crateFlutterFfiSessionInputKey(
  sessionId: sessionId,
  name: name,
  down: down,
  press: press,
  alt: alt,
  ctrl: ctrl,
  shift: shift,
  command: command,
);

Future<void> sessionInputString({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionInputString(
  sessionId: sessionId,
  value: value,
);

Future<void> sessionSendChat({
  required UuidValue sessionId,
  required String text,
}) => RustLib.instance.api.crateFlutterFfiSessionSendChat(
  sessionId: sessionId,
  text: text,
);

Future<void> sessionOpenTerminal({
  required UuidValue sessionId,
  required int terminalId,
  required int rows,
  required int cols,
}) => RustLib.instance.api.crateFlutterFfiSessionOpenTerminal(
  sessionId: sessionId,
  terminalId: terminalId,
  rows: rows,
  cols: cols,
);

Future<void> sessionSendTerminalInput({
  required UuidValue sessionId,
  required int terminalId,
  required String data,
}) => RustLib.instance.api.crateFlutterFfiSessionSendTerminalInput(
  sessionId: sessionId,
  terminalId: terminalId,
  data: data,
);

Future<void> sessionResizeTerminal({
  required UuidValue sessionId,
  required int terminalId,
  required int rows,
  required int cols,
}) => RustLib.instance.api.crateFlutterFfiSessionResizeTerminal(
  sessionId: sessionId,
  terminalId: terminalId,
  rows: rows,
  cols: cols,
);

Future<void> sessionCloseTerminal({
  required UuidValue sessionId,
  required int terminalId,
}) => RustLib.instance.api.crateFlutterFfiSessionCloseTerminal(
  sessionId: sessionId,
  terminalId: terminalId,
);

Future<void> sessionPeerOption({
  required UuidValue sessionId,
  required String name,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionPeerOption(
  sessionId: sessionId,
  name: name,
  value: value,
);

Future<String> sessionGetPeerOption({
  required UuidValue sessionId,
  required String name,
}) => RustLib.instance.api.crateFlutterFfiSessionGetPeerOption(
  sessionId: sessionId,
  name: name,
);

Future<void> sessionInputOsPassword({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionInputOsPassword(
  sessionId: sessionId,
  value: value,
);

Future<void> sessionReadRemoteDir({
  required UuidValue sessionId,
  required String path,
  required bool includeHidden,
}) => RustLib.instance.api.crateFlutterFfiSessionReadRemoteDir(
  sessionId: sessionId,
  path: path,
  includeHidden: includeHidden,
);

Future<void> sessionSendFiles({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required String to,
  required int fileNum,
  required bool includeHidden,
  required bool isRemote,
  required bool isDir,
}) => RustLib.instance.api.crateFlutterFfiSessionSendFiles(
  sessionId: sessionId,
  actId: actId,
  path: path,
  to: to,
  fileNum: fileNum,
  includeHidden: includeHidden,
  isRemote: isRemote,
  isDir: isDir,
);

Future<void> sessionSetConfirmOverrideFile({
  required UuidValue sessionId,
  required int actId,
  required int fileNum,
  required bool needOverride,
  required bool remember,
  required bool isUpload,
}) => RustLib.instance.api.crateFlutterFfiSessionSetConfirmOverrideFile(
  sessionId: sessionId,
  actId: actId,
  fileNum: fileNum,
  needOverride: needOverride,
  remember: remember,
  isUpload: isUpload,
);

Future<void> sessionRemoveFile({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required int fileNum,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionRemoveFile(
  sessionId: sessionId,
  actId: actId,
  path: path,
  fileNum: fileNum,
  isRemote: isRemote,
);

Future<void> sessionReadDirToRemoveRecursive({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required bool isRemote,
  required bool showHidden,
}) => RustLib.instance.api.crateFlutterFfiSessionReadDirToRemoveRecursive(
  sessionId: sessionId,
  actId: actId,
  path: path,
  isRemote: isRemote,
  showHidden: showHidden,
);

Future<void> sessionRemoveAllEmptyDirs({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionRemoveAllEmptyDirs(
  sessionId: sessionId,
  actId: actId,
  path: path,
  isRemote: isRemote,
);

Future<void> sessionCancelJob({
  required UuidValue sessionId,
  required int actId,
}) => RustLib.instance.api.crateFlutterFfiSessionCancelJob(
  sessionId: sessionId,
  actId: actId,
);

Future<void> sessionCreateDir({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionCreateDir(
  sessionId: sessionId,
  actId: actId,
  path: path,
  isRemote: isRemote,
);

Future<String> sessionReadLocalDirSync({
  required UuidValue sessionId,
  required String path,
  required bool showHidden,
}) => RustLib.instance.api.crateFlutterFfiSessionReadLocalDirSync(
  sessionId: sessionId,
  path: path,
  showHidden: showHidden,
);

Future<String> sessionReadLocalEmptyDirsRecursiveSync({
  required UuidValue sessionId,
  required String path,
  required bool includeHidden,
}) =>
    RustLib.instance.api.crateFlutterFfiSessionReadLocalEmptyDirsRecursiveSync(
      sessionId: sessionId,
      path: path,
      includeHidden: includeHidden,
    );

Future<void> sessionReadRemoteEmptyDirsRecursiveSync({
  required UuidValue sessionId,
  required String path,
  required bool includeHidden,
}) =>
    RustLib.instance.api.crateFlutterFfiSessionReadRemoteEmptyDirsRecursiveSync(
      sessionId: sessionId,
      path: path,
      includeHidden: includeHidden,
    );

Future<String> sessionGetPlatform({
  required UuidValue sessionId,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionGetPlatform(
  sessionId: sessionId,
  isRemote: isRemote,
);

Future<void> sessionLoadLastTransferJobs({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionLoadLastTransferJobs(
      sessionId: sessionId,
    );

Future<void> sessionAddJob({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required String to,
  required int fileNum,
  required bool includeHidden,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionAddJob(
  sessionId: sessionId,
  actId: actId,
  path: path,
  to: to,
  fileNum: fileNum,
  includeHidden: includeHidden,
  isRemote: isRemote,
);

Future<void> sessionResumeJob({
  required UuidValue sessionId,
  required int actId,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionResumeJob(
  sessionId: sessionId,
  actId: actId,
  isRemote: isRemote,
);

Future<void> sessionRenameFile({
  required UuidValue sessionId,
  required int actId,
  required String path,
  required String newName,
  required bool isRemote,
}) => RustLib.instance.api.crateFlutterFfiSessionRenameFile(
  sessionId: sessionId,
  actId: actId,
  path: path,
  newName: newName,
  isRemote: isRemote,
);

Future<void> sessionElevateDirect({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionElevateDirect(sessionId: sessionId);

Future<void> sessionElevateWithLogon({
  required UuidValue sessionId,
  required String username,
  required String password,
}) => RustLib.instance.api.crateFlutterFfiSessionElevateWithLogon(
  sessionId: sessionId,
  username: username,
  password: password,
);

Future<void> sessionSwitchSides({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionSwitchSides(sessionId: sessionId);

Future<void> sessionChangeResolution({
  required UuidValue sessionId,
  required int display,
  required int width,
  required int height,
}) => RustLib.instance.api.crateFlutterFfiSessionChangeResolution(
  sessionId: sessionId,
  display: display,
  width: width,
  height: height,
);

Future<void> sessionSetSize({
  required UuidValue sessionId,
  required int display,
  required int width,
  required int height,
}) => RustLib.instance.api.crateFlutterFfiSessionSetSize(
  sessionId: sessionId,
  display: display,
  width: width,
  height: height,
);

Future<void> sessionSendSelectedSessionId({
  required UuidValue sessionId,
  required String sid,
}) => RustLib.instance.api.crateFlutterFfiSessionSendSelectedSessionId(
  sessionId: sessionId,
  sid: sid,
);

Future<List<String>> mainGetSoundInputs() =>
    RustLib.instance.api.crateFlutterFfiMainGetSoundInputs();

String mainGetLoginDeviceInfo() =>
    RustLib.instance.api.crateFlutterFfiMainGetLoginDeviceInfo();

Future<void> mainChangeId({required String newId}) =>
    RustLib.instance.api.crateFlutterFfiMainChangeId(newId: newId);

Future<String> mainGetAsyncStatus() =>
    RustLib.instance.api.crateFlutterFfiMainGetAsyncStatus();

Future<String?> mainGetHttpStatus({required String url}) =>
    RustLib.instance.api.crateFlutterFfiMainGetHttpStatus(url: url);

Future<String> mainGetOption({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetOption(key: key);

String mainGetOptionSync({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetOptionSync(key: key);

Future<String> mainGetError() =>
    RustLib.instance.api.crateFlutterFfiMainGetError();

bool mainShowOption({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainShowOption(key: key);

Future<void> mainSetOption({required String key, required String value}) =>
    RustLib.instance.api.crateFlutterFfiMainSetOption(key: key, value: value);

Future<String> mainGetOptions() =>
    RustLib.instance.api.crateFlutterFfiMainGetOptions();

String mainGetOptionsSync() =>
    RustLib.instance.api.crateFlutterFfiMainGetOptionsSync();

Future<void> mainSetOptions({required String json}) =>
    RustLib.instance.api.crateFlutterFfiMainSetOptions(json: json);

Future<String> mainTestIfValidServer({
  required String server,
  required bool testWithProxy,
}) => RustLib.instance.api.crateFlutterFfiMainTestIfValidServer(
  server: server,
  testWithProxy: testWithProxy,
);

Future<void> mainSetSocks({
  required String proxy,
  required String username,
  required String password,
}) => RustLib.instance.api.crateFlutterFfiMainSetSocks(
  proxy: proxy,
  username: username,
  password: password,
);

Future<bool> mainGetProxyStatus() =>
    RustLib.instance.api.crateFlutterFfiMainGetProxyStatus();

Future<List<String>> mainGetSocks() =>
    RustLib.instance.api.crateFlutterFfiMainGetSocks();

Future<String> mainGetAppName() =>
    RustLib.instance.api.crateFlutterFfiMainGetAppName();

String mainGetAppNameSync() =>
    RustLib.instance.api.crateFlutterFfiMainGetAppNameSync();

String mainUriPrefixSync() =>
    RustLib.instance.api.crateFlutterFfiMainUriPrefixSync();

Future<String> mainGetLicense() =>
    RustLib.instance.api.crateFlutterFfiMainGetLicense();

Future<String> mainGetVersion() =>
    RustLib.instance.api.crateFlutterFfiMainGetVersion();

Future<List<String>> mainGetFav() =>
    RustLib.instance.api.crateFlutterFfiMainGetFav();

Future<void> mainStoreFav({required List<String> favs}) =>
    RustLib.instance.api.crateFlutterFfiMainStoreFav(favs: favs);

String mainGetPeerSync({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainGetPeerSync(id: id);

Future<String> mainGetLanPeers() =>
    RustLib.instance.api.crateFlutterFfiMainGetLanPeers();

Future<String> mainGetConnectStatus() =>
    RustLib.instance.api.crateFlutterFfiMainGetConnectStatus();

Future<void> mainCheckConnectStatus() =>
    RustLib.instance.api.crateFlutterFfiMainCheckConnectStatus();

Future<bool> mainIsUsingPublicServer() =>
    RustLib.instance.api.crateFlutterFfiMainIsUsingPublicServer();

Future<void> mainDiscover() =>
    RustLib.instance.api.crateFlutterFfiMainDiscover();

Future<String> mainGetApiServer() =>
    RustLib.instance.api.crateFlutterFfiMainGetApiServer();

/// Registers this device against the configured API server.
///
/// `deploy_device` already handles every platform - desktop reads and rewrites
/// the id over IPC - so there is no reason to restrict enrolment to phones.
Future<String> mainDeployDevice({required String token, required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainDeployDevice(token: token, id: id);

String mainResolveAvatarUrl({required String avatar}) =>
    RustLib.instance.api.crateFlutterFfiMainResolveAvatarUrl(avatar: avatar);

Future<void> mainHttpRequest({
  required String url,
  required String method,
  String? body,
  required String header,
}) => RustLib.instance.api.crateFlutterFfiMainHttpRequest(
  url: url,
  method: method,
  body: body,
  header: header,
);

String mainGetLocalOption({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetLocalOption(key: key);

bool mainGetUseTextureRender() =>
    RustLib.instance.api.crateFlutterFfiMainGetUseTextureRender();

String mainGetEnv({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetEnv(key: key);

void mainSetEnv({required String key, String? value}) =>
    RustLib.instance.api.crateFlutterFfiMainSetEnv(key: key, value: value);

Future<void> mainSetLocalOption({required String key, required String value}) =>
    RustLib.instance.api.crateFlutterFfiMainSetLocalOption(
      key: key,
      value: value,
    );

Future<String> mainHandleWaylandScreencastRestoreToken({
  required String key,
  required String value,
}) =>
    RustLib.instance.api.crateFlutterFfiMainHandleWaylandScreencastRestoreToken(
      key: key,
      value: value,
    );

String mainGetInputSource() =>
    RustLib.instance.api.crateFlutterFfiMainGetInputSource();

Future<void> mainSetInputSource({
  required UuidValue sessionId,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiMainSetInputSource(
  sessionId: sessionId,
  value: value,
);

/// Set cursor position (for pointer lock re-centering).
///
/// # Returns
/// - `true`: cursor position was successfully set
/// - `false`: operation failed or not supported
///
/// # Platform behavior
/// - Windows/macOS/Linux: attempts to move the cursor to (x, y)
/// - Android/iOS: no-op, always returns `false`
bool mainSetCursorPosition({required int x, required int y}) =>
    RustLib.instance.api.crateFlutterFfiMainSetCursorPosition(x: x, y: y);

/// Clip cursor to a rectangle (for pointer lock).
///
/// When `enable` is true, the cursor is clipped to the rectangle defined by
/// `left`, `top`, `right`, `bottom`. When `enable` is false, the rectangle
/// values are ignored and the cursor is unclipped.
///
/// # Returns
/// - `true`: operation succeeded or no-op completed
/// - `false`: operation failed
///
/// # Platform behavior
/// - Windows: uses ClipCursor API to confine cursor to the specified rectangle
/// - macOS: uses CGAssociateMouseAndMouseCursorPosition for pointer lock effect;
///   the rect coordinates are ignored (only Some/None matters)
/// - Linux: no-op, always returns `true`; use pointer warping for similar effect
/// - Android/iOS: no-op, always returns `false`
bool mainClipCursor({
  required int left,
  required int top,
  required int right,
  required int bottom,
  required bool enable,
}) => RustLib.instance.api.crateFlutterFfiMainClipCursor(
  left: left,
  top: top,
  right: right,
  bottom: bottom,
  enable: enable,
);

Future<String> mainGetMyId() =>
    RustLib.instance.api.crateFlutterFfiMainGetMyId();

Future<String> mainGetUuid() =>
    RustLib.instance.api.crateFlutterFfiMainGetUuid();

Future<String> mainGetPeerOption({required String id, required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetPeerOption(id: id, key: key);

String mainGetPeerOptionSync({required String id, required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetPeerOptionSync(id: id, key: key);

String mainGetPeerFlutterOptionSync({required String id, required String k}) =>
    RustLib.instance.api.crateFlutterFfiMainGetPeerFlutterOptionSync(
      id: id,
      k: k,
    );

void mainSetPeerFlutterOptionSync({
  required String id,
  required String k,
  required String v,
}) => RustLib.instance.api.crateFlutterFfiMainSetPeerFlutterOptionSync(
  id: id,
  k: k,
  v: v,
);

Future<void> mainSetPeerOption({
  required String id,
  required String key,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiMainSetPeerOption(
  id: id,
  key: key,
  value: value,
);

bool mainSetPeerOptionSync({
  required String id,
  required String key,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiMainSetPeerOptionSync(
  id: id,
  key: key,
  value: value,
);

Future<void> mainSetPeerAlias({required String id, required String alias}) =>
    RustLib.instance.api.crateFlutterFfiMainSetPeerAlias(id: id, alias: alias);

Future<String> mainGetNewStoredPeers() =>
    RustLib.instance.api.crateFlutterFfiMainGetNewStoredPeers();

Future<void> mainForgetPassword({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainForgetPassword(id: id);

Future<bool> mainPeerHasPassword({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainPeerHasPassword(id: id);

Future<bool> mainPeerExists({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainPeerExists(id: id);

Future<void> mainLoadRecentPeers() =>
    RustLib.instance.api.crateFlutterFfiMainLoadRecentPeers();

Future<String> mainLoadRecentPeersForAb({required String filter}) => RustLib
    .instance
    .api
    .crateFlutterFfiMainLoadRecentPeersForAb(filter: filter);

Future<void> mainLoadFavPeers() =>
    RustLib.instance.api.crateFlutterFfiMainLoadFavPeers();

Future<void> mainLoadLanPeers() =>
    RustLib.instance.api.crateFlutterFfiMainLoadLanPeers();

Future<void> mainRemoveDiscovered({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainRemoveDiscovered(id: id);

Future<void> mainChangeTheme({required String dark}) =>
    RustLib.instance.api.crateFlutterFfiMainChangeTheme(dark: dark);

Future<void> mainChangeLanguage({required String lang}) =>
    RustLib.instance.api.crateFlutterFfiMainChangeLanguage(lang: lang);

String mainVideoSaveDirectory({required bool root}) =>
    RustLib.instance.api.crateFlutterFfiMainVideoSaveDirectory(root: root);

Future<void> mainSetUserDefaultOption({
  required String key,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiMainSetUserDefaultOption(
  key: key,
  value: value,
);

String mainGetUserDefaultOption({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetUserDefaultOption(key: key);

Future<String> mainHandleRelayId({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainHandleRelayId(id: id);

bool mainIsOptionFixed({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainIsOptionFixed(key: key);

String mainGetMainDisplay() =>
    RustLib.instance.api.crateFlutterFfiMainGetMainDisplay();

String mainGetDisplays() =>
    RustLib.instance.api.crateFlutterFfiMainGetDisplays();

Future<void> sessionAddPortForward({
  required UuidValue sessionId,
  required int localPort,
  required String remoteHost,
  required int remotePort,
}) => RustLib.instance.api.crateFlutterFfiSessionAddPortForward(
  sessionId: sessionId,
  localPort: localPort,
  remoteHost: remoteHost,
  remotePort: remotePort,
);

Future<void> sessionRemovePortForward({
  required UuidValue sessionId,
  required int localPort,
}) => RustLib.instance.api.crateFlutterFfiSessionRemovePortForward(
  sessionId: sessionId,
  localPort: localPort,
);

Future<void> sessionNewRdp({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionNewRdp(sessionId: sessionId);

Future<void> sessionRequestVoiceCall({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionRequestVoiceCall(sessionId: sessionId);

Future<void> sessionCloseVoiceCall({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionCloseVoiceCall(sessionId: sessionId);

String? sessionGetConnToken({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetConnToken(sessionId: sessionId);

Future<void> cmHandleIncomingVoiceCall({
  required int id,
  required bool accept,
}) => RustLib.instance.api.crateFlutterFfiCmHandleIncomingVoiceCall(
  id: id,
  accept: accept,
);

Future<void> cmCloseVoiceCall({required int id}) =>
    RustLib.instance.api.crateFlutterFfiCmCloseVoiceCall(id: id);

Future<void> setVoiceCallInputDevice({
  required bool isCm,
  required String device,
}) => RustLib.instance.api.crateFlutterFfiSetVoiceCallInputDevice(
  isCm: isCm,
  device: device,
);

Future<String> getVoiceCallInputDevice({required bool isCm}) =>
    RustLib.instance.api.crateFlutterFfiGetVoiceCallInputDevice(isCm: isCm);

Future<String> mainGetLastRemoteId() =>
    RustLib.instance.api.crateFlutterFfiMainGetLastRemoteId();

Future<void> mainGetSoftwareUpdateUrl() =>
    RustLib.instance.api.crateFlutterFfiMainGetSoftwareUpdateUrl();

Future<String> mainGetHomeDir() =>
    RustLib.instance.api.crateFlutterFfiMainGetHomeDir();

Future<String> mainGetLangs() =>
    RustLib.instance.api.crateFlutterFfiMainGetLangs();

Future<String> mainGetTemporaryPassword() =>
    RustLib.instance.api.crateFlutterFfiMainGetTemporaryPassword();

Future<bool> mainSetPermanentPasswordWithResult({required String password}) =>
    RustLib.instance.api.crateFlutterFfiMainSetPermanentPasswordWithResult(
      password: password,
    );

Future<String> mainGetFingerprint() =>
    RustLib.instance.api.crateFlutterFfiMainGetFingerprint();

Future<String> cmGetClientsState() =>
    RustLib.instance.api.crateFlutterFfiCmGetClientsState();

Future<String?> cmCheckClientsLength({required int length}) =>
    RustLib.instance.api.crateFlutterFfiCmCheckClientsLength(length: length);

Future<int> cmGetClientsLength() =>
    RustLib.instance.api.crateFlutterFfiCmGetClientsLength();

Future<void> mainInit({
  required String appDir,
  required String customClientConfig,
}) => RustLib.instance.api.crateFlutterFfiMainInit(
  appDir: appDir,
  customClientConfig: customClientConfig,
);

Future<void> mainDeviceId({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainDeviceId(id: id);

Future<void> mainDeviceName({required String name}) =>
    RustLib.instance.api.crateFlutterFfiMainDeviceName(name: name);

Future<void> mainRemovePeer({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainRemovePeer(id: id);

bool mainHasHwcodec() => RustLib.instance.api.crateFlutterFfiMainHasHwcodec();

bool mainHasVram() => RustLib.instance.api.crateFlutterFfiMainHasVram();

String mainSupportedHwdecodings() =>
    RustLib.instance.api.crateFlutterFfiMainSupportedHwdecodings();

Future<bool> mainIsRoot() => RustLib.instance.api.crateFlutterFfiMainIsRoot();

int getDoubleClickTime() =>
    RustLib.instance.api.crateFlutterFfiGetDoubleClickTime();

Future<void> mainStartDbusServer() =>
    RustLib.instance.api.crateFlutterFfiMainStartDbusServer();

Future<void> mainSaveAb({required String json}) =>
    RustLib.instance.api.crateFlutterFfiMainSaveAb(json: json);

Future<void> mainClearAb() => RustLib.instance.api.crateFlutterFfiMainClearAb();

Future<String> mainLoadAb() => RustLib.instance.api.crateFlutterFfiMainLoadAb();

Future<void> mainSaveGroup({required String json}) =>
    RustLib.instance.api.crateFlutterFfiMainSaveGroup(json: json);

Future<void> mainClearGroup() =>
    RustLib.instance.api.crateFlutterFfiMainClearGroup();

Future<String> mainLoadGroup() =>
    RustLib.instance.api.crateFlutterFfiMainLoadGroup();

Future<void> sessionSendPointer({
  required UuidValue sessionId,
  required String msg,
}) => RustLib.instance.api.crateFlutterFfiSessionSendPointer(
  sessionId: sessionId,
  msg: msg,
);

/// Send mouse event from Flutter to the remote peer.
///
/// # Relative Mouse Mode Message Contract
///
/// When the message contains a `relative_mouse_mode` field, this function validates
/// and filters activation/deactivation markers.
///
/// **Mode Authority:**
/// The Flutter InputModel is authoritative for relative mouse mode activation/deactivation.
/// The server (via `input_service.rs`) only consumes forwarded delta movements and tracks
/// relative movement processing state, but does NOT control mode activation/deactivation.
///
/// **Deactivation Markers are Local-Only:**
/// Deactivation markers (`relative_mouse_mode: "0"`) are NEVER forwarded to the server.
/// They are handled entirely on the client side to reset local UI state (cursor visibility,
/// pointer lock, etc.). The server does not rely on deactivation markers and should not
/// expect to receive them.
///
/// **Contract (Flutter side MUST adhere to):**
/// 1. `relative_mouse_mode` field is ONLY present on activation/deactivation marker messages,
///    NEVER on normal pointer events (move, button, scroll).
/// 2. Deactivation marker: `{"relative_mouse_mode": "0"}` - local-only, never forwarded.
/// 3. Activation marker: `{"relative_mouse_mode": "1", "type": "move_relative", "x": "0", "y": "0"}`
///    - MUST use `type="move_relative"` with `x="0"` and `y="0"` (safe no-op).
///    - Any other combination is dropped to prevent accidental cursor movement.
///
/// If these assumptions are violated (e.g., `relative_mouse_mode` is added to normal events),
/// legitimate mouse events may be silently dropped by the early-return logic below.
Future<void> sessionSendMouse({
  required UuidValue sessionId,
  required String msg,
}) => RustLib.instance.api.crateFlutterFfiSessionSendMouse(
  sessionId: sessionId,
  msg: msg,
);

Future<void> sessionRestartRemoteDevice({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionRestartRemoteDevice(
      sessionId: sessionId,
    );

String sessionGetAuditServerSync({
  required UuidValue sessionId,
  required String typ,
}) => RustLib.instance.api.crateFlutterFfiSessionGetAuditServerSync(
  sessionId: sessionId,
  typ: typ,
);

Future<void> sessionSendNote({
  required UuidValue sessionId,
  required String note,
}) => RustLib.instance.api.crateFlutterFfiSessionSendNote(
  sessionId: sessionId,
  note: note,
);

String sessionGetLastAuditNote({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetLastAuditNote(sessionId: sessionId);

Future<void> sessionSetAuditGuid({
  required UuidValue sessionId,
  required String guid,
}) => RustLib.instance.api.crateFlutterFfiSessionSetAuditGuid(
  sessionId: sessionId,
  guid: guid,
);

String sessionGetAuditGuid({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetAuditGuid(sessionId: sessionId);

String sessionGetConnSessionId({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionGetConnSessionId(sessionId: sessionId);

Future<String> sessionAlternativeCodecs({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSessionAlternativeCodecs(
      sessionId: sessionId,
    );

Future<void> sessionChangePreferCodec({required UuidValue sessionId}) => RustLib
    .instance
    .api
    .crateFlutterFfiSessionChangePreferCodec(sessionId: sessionId);

Future<void> sessionOnWaitingForImageDialogShow({
  required UuidValue sessionId,
}) => RustLib.instance.api.crateFlutterFfiSessionOnWaitingForImageDialogShow(
  sessionId: sessionId,
);

Future<void> sessionToggleVirtualDisplay({
  required UuidValue sessionId,
  required int index,
  required bool on_,
}) => RustLib.instance.api.crateFlutterFfiSessionToggleVirtualDisplay(
  sessionId: sessionId,
  index: index,
  on_: on_,
);

Future<void> sessionPrinterResponse({
  required UuidValue sessionId,
  required int id,
  required String path,
  required String printerName,
}) => RustLib.instance.api.crateFlutterFfiSessionPrinterResponse(
  sessionId: sessionId,
  id: id,
  path: path,
  printerName: printerName,
);

Future<void> mainSetHomeDir({required String home}) =>
    RustLib.instance.api.crateFlutterFfiMainSetHomeDir(home: home);

String mainGetDataDirIos({required String appDir}) =>
    RustLib.instance.api.crateFlutterFfiMainGetDataDirIos(appDir: appDir);

Future<void> mainStopService() =>
    RustLib.instance.api.crateFlutterFfiMainStopService();

Future<void> mainStartService() =>
    RustLib.instance.api.crateFlutterFfiMainStartService();

Future<void> mainUpdateTemporaryPassword() =>
    RustLib.instance.api.crateFlutterFfiMainUpdateTemporaryPassword();

Future<bool> mainCheckSuperUserPermission() =>
    RustLib.instance.api.crateFlutterFfiMainCheckSuperUserPermission();

String mainGetUnlockPin() =>
    RustLib.instance.api.crateFlutterFfiMainGetUnlockPin();

String mainSetUnlockPin({required String pin}) =>
    RustLib.instance.api.crateFlutterFfiMainSetUnlockPin(pin: pin);

Future<void> mainCheckMouseTime() =>
    RustLib.instance.api.crateFlutterFfiMainCheckMouseTime();

Future<double> mainGetMouseTime() =>
    RustLib.instance.api.crateFlutterFfiMainGetMouseTime();

Future<void> mainWol({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainWol(id: id);

Future<void> mainCreateShortcut({required String id}) =>
    RustLib.instance.api.crateFlutterFfiMainCreateShortcut(id: id);

Future<void> cmSendChat({required int connId, required String msg}) =>
    RustLib.instance.api.crateFlutterFfiCmSendChat(connId: connId, msg: msg);

Future<void> cmLoginRes({required int connId, required bool res}) =>
    RustLib.instance.api.crateFlutterFfiCmLoginRes(connId: connId, res: res);

Future<void> cmCloseConnection({required int connId}) =>
    RustLib.instance.api.crateFlutterFfiCmCloseConnection(connId: connId);

Future<void> cmRemoveDisconnectedConnection({required int connId}) => RustLib
    .instance
    .api
    .crateFlutterFfiCmRemoveDisconnectedConnection(connId: connId);

Future<void> cmCheckClickTime({required int connId}) =>
    RustLib.instance.api.crateFlutterFfiCmCheckClickTime(connId: connId);

Future<double> cmGetClickTime() =>
    RustLib.instance.api.crateFlutterFfiCmGetClickTime();

Future<void> cmSwitchPermission({
  required int connId,
  required String name,
  required bool enabled,
}) => RustLib.instance.api.crateFlutterFfiCmSwitchPermission(
  connId: connId,
  name: name,
  enabled: enabled,
);

bool cmCanElevate() => RustLib.instance.api.crateFlutterFfiCmCanElevate();

Future<void> cmElevatePortable({required int connId}) =>
    RustLib.instance.api.crateFlutterFfiCmElevatePortable(connId: connId);

Future<void> cmSwitchBack({required int connId}) =>
    RustLib.instance.api.crateFlutterFfiCmSwitchBack(connId: connId);

Future<String> cmGetConfig({required String name}) =>
    RustLib.instance.api.crateFlutterFfiCmGetConfig(name: name);

Future<String> mainGetBuildDate() =>
    RustLib.instance.api.crateFlutterFfiMainGetBuildDate();

String translate({required String name, required String locale}) =>
    RustLib.instance.api.crateFlutterFfiTranslate(name: name, locale: locale);

int sessionGetRgbaSize({required UuidValue sessionId, required int display}) =>
    RustLib.instance.api.crateFlutterFfiSessionGetRgbaSize(
      sessionId: sessionId,
      display: display,
    );

void sessionNextRgba({required UuidValue sessionId, required int display}) =>
    RustLib.instance.api.crateFlutterFfiSessionNextRgba(
      sessionId: sessionId,
      display: display,
    );

void sessionRegisterPixelbufferTexture({
  required UuidValue sessionId,
  required int display,
  required int ptr,
}) => RustLib.instance.api.crateFlutterFfiSessionRegisterPixelbufferTexture(
  sessionId: sessionId,
  display: display,
  ptr: ptr,
);

void sessionRegisterGpuTexture({
  required UuidValue sessionId,
  required int display,
  required int ptr,
}) => RustLib.instance.api.crateFlutterFfiSessionRegisterGpuTexture(
  sessionId: sessionId,
  display: display,
  ptr: ptr,
);

Future<void> queryOnlines({required List<String> ids}) =>
    RustLib.instance.api.crateFlutterFfiQueryOnlines(ids: ids);

int versionToNumber({required String v}) =>
    RustLib.instance.api.crateFlutterFfiVersionToNumber(v: v);

Future<bool> optionSynced() =>
    RustLib.instance.api.crateFlutterFfiOptionSynced();

bool mainIsInstalled() => RustLib.instance.api.crateFlutterFfiMainIsInstalled();

void mainInitInputSource() =>
    RustLib.instance.api.crateFlutterFfiMainInitInputSource();

bool mainIsInstalledLowerVersion() =>
    RustLib.instance.api.crateFlutterFfiMainIsInstalledLowerVersion();

bool mainIsInstalledDaemon({required bool prompt}) =>
    RustLib.instance.api.crateFlutterFfiMainIsInstalledDaemon(prompt: prompt);

bool mainIsProcessTrusted({required bool prompt}) =>
    RustLib.instance.api.crateFlutterFfiMainIsProcessTrusted(prompt: prompt);

bool mainIsCanScreenRecording({required bool prompt}) => RustLib.instance.api
    .crateFlutterFfiMainIsCanScreenRecording(prompt: prompt);

bool mainIsCanInputMonitoring({required bool prompt}) => RustLib.instance.api
    .crateFlutterFfiMainIsCanInputMonitoring(prompt: prompt);

bool mainIsShareRdp() => RustLib.instance.api.crateFlutterFfiMainIsShareRdp();

Future<void> mainSetShareRdp({required bool enable}) =>
    RustLib.instance.api.crateFlutterFfiMainSetShareRdp(enable: enable);

bool mainGotoInstall() => RustLib.instance.api.crateFlutterFfiMainGotoInstall();

String mainGetNewVersion() =>
    RustLib.instance.api.crateFlutterFfiMainGetNewVersion();

bool mainUpdateMe() => RustLib.instance.api.crateFlutterFfiMainUpdateMe();

Future<void> setCurSessionId({required UuidValue sessionId}) =>
    RustLib.instance.api.crateFlutterFfiSetCurSessionId(sessionId: sessionId);

bool installShowRunWithoutInstall() =>
    RustLib.instance.api.crateFlutterFfiInstallShowRunWithoutInstall();

Future<void> installRunWithoutInstall() =>
    RustLib.instance.api.crateFlutterFfiInstallRunWithoutInstall();

Future<void> installInstallMe({
  required String options,
  required String path,
}) => RustLib.instance.api.crateFlutterFfiInstallInstallMe(
  options: options,
  path: path,
);

String installInstallPath() =>
    RustLib.instance.api.crateFlutterFfiInstallInstallPath();

String installInstallOptions() =>
    RustLib.instance.api.crateFlutterFfiInstallInstallOptions();

Future<void> mainAccountAuth({required String op, required bool rememberMe}) =>
    RustLib.instance.api.crateFlutterFfiMainAccountAuth(
      op: op,
      rememberMe: rememberMe,
    );

Future<void> mainAccountAuthCancel() =>
    RustLib.instance.api.crateFlutterFfiMainAccountAuthCancel();

Future<String> mainAccountAuthResult() =>
    RustLib.instance.api.crateFlutterFfiMainAccountAuthResult();

Future<void> mainOnMainWindowClose() =>
    RustLib.instance.api.crateFlutterFfiMainOnMainWindowClose();

bool mainCurrentIsWayland() =>
    RustLib.instance.api.crateFlutterFfiMainCurrentIsWayland();

bool mainIsLoginWayland() =>
    RustLib.instance.api.crateFlutterFfiMainIsLoginWayland();

bool mainHideDock() => RustLib.instance.api.crateFlutterFfiMainHideDock();

bool mainHasFileClipboard() =>
    RustLib.instance.api.crateFlutterFfiMainHasFileClipboard();

bool mainHasGpuTextureRender() =>
    RustLib.instance.api.crateFlutterFfiMainHasGpuTextureRender();

Future<void> cmInit() => RustLib.instance.api.crateFlutterFfiCmInit();

/// Start an ipc server for receiving the url scheme.
///
/// * Should only be called in the main flutter window.
/// * macOS only
Future<void> mainStartIpcUrlServer() =>
    RustLib.instance.api.crateFlutterFfiMainStartIpcUrlServer();

Future<void> mainTestWallpaper({required int second}) =>
    RustLib.instance.api.crateFlutterFfiMainTestWallpaper(second: second);

Future<bool> mainSupportRemoveWallpaper() =>
    RustLib.instance.api.crateFlutterFfiMainSupportRemoveWallpaper();

bool isIncomingOnly() => RustLib.instance.api.crateFlutterFfiIsIncomingOnly();

bool isOutgoingOnly() => RustLib.instance.api.crateFlutterFfiIsOutgoingOnly();

bool isCustomClient() => RustLib.instance.api.crateFlutterFfiIsCustomClient();

bool isDisableSettings() =>
    RustLib.instance.api.crateFlutterFfiIsDisableSettings();

bool isDisableAb() => RustLib.instance.api.crateFlutterFfiIsDisableAb();

bool isDisableAccount() =>
    RustLib.instance.api.crateFlutterFfiIsDisableAccount();

bool isDisableGroupPanel() =>
    RustLib.instance.api.crateFlutterFfiIsDisableGroupPanel();

bool isDisableInstallation() =>
    RustLib.instance.api.crateFlutterFfiIsDisableInstallation();

Future<bool> isPresetPassword() =>
    RustLib.instance.api.crateFlutterFfiIsPresetPassword();

bool isPresetPasswordMobileOnly() =>
    RustLib.instance.api.crateFlutterFfiIsPresetPasswordMobileOnly();

/// Send a url scheme through the ipc.
///
/// * macOS only
Future<void> sendUrlScheme({required String url}) =>
    RustLib.instance.api.crateFlutterFfiSendUrlScheme(url: url);

Future<void> pluginEvent({
  required String id,
  required String peer,
  required List<int> event,
}) => RustLib.instance.api.crateFlutterFfiPluginEvent(
  id: id,
  peer: peer,
  event: event,
);

Stream<EventToUI> pluginRegisterEventStream({required String id}) =>
    RustLib.instance.api.crateFlutterFfiPluginRegisterEventStream(id: id);

String? pluginGetSessionOption({
  required String id,
  required String peer,
  required String key,
}) => RustLib.instance.api.crateFlutterFfiPluginGetSessionOption(
  id: id,
  peer: peer,
  key: key,
);

Future<void> pluginSetSessionOption({
  required String id,
  required String peer,
  required String key,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiPluginSetSessionOption(
  id: id,
  peer: peer,
  key: key,
  value: value,
);

String? pluginGetSharedOption({required String id, required String key}) =>
    RustLib.instance.api.crateFlutterFfiPluginGetSharedOption(id: id, key: key);

Future<void> pluginSetSharedOption({
  required String id,
  required String key,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiPluginSetSharedOption(
  id: id,
  key: key,
  value: value,
);

Future<void> pluginReload({required String id}) =>
    RustLib.instance.api.crateFlutterFfiPluginReload(id: id);

void pluginEnable({required String id, required bool v}) =>
    RustLib.instance.api.crateFlutterFfiPluginEnable(id: id, v: v);

bool pluginIsEnabled({required String id}) =>
    RustLib.instance.api.crateFlutterFfiPluginIsEnabled(id: id);

bool pluginFeatureIsEnabled() =>
    RustLib.instance.api.crateFlutterFfiPluginFeatureIsEnabled();

Future<void> pluginSyncUi({required String syncTo}) =>
    RustLib.instance.api.crateFlutterFfiPluginSyncUi(syncTo: syncTo);

Future<void> pluginListReload() =>
    RustLib.instance.api.crateFlutterFfiPluginListReload();

Future<void> pluginInstall({required String id, required bool b}) =>
    RustLib.instance.api.crateFlutterFfiPluginInstall(id: id, b: b);

bool isSupportMultiUiSession({required String version}) => RustLib.instance.api
    .crateFlutterFfiIsSupportMultiUiSession(version: version);

bool isSelinuxEnforcing() =>
    RustLib.instance.api.crateFlutterFfiIsSelinuxEnforcing();

String mainDefaultPrivacyModeImpl() =>
    RustLib.instance.api.crateFlutterFfiMainDefaultPrivacyModeImpl();

String mainSupportedPrivacyModeImpls() =>
    RustLib.instance.api.crateFlutterFfiMainSupportedPrivacyModeImpls();

String mainSupportedInputSource() =>
    RustLib.instance.api.crateFlutterFfiMainSupportedInputSource();

Future<String> mainGenerate2Fa() =>
    RustLib.instance.api.crateFlutterFfiMainGenerate2Fa();

Future<bool> mainVerify2Fa({required String code}) =>
    RustLib.instance.api.crateFlutterFfiMainVerify2Fa(code: code);

bool mainHasValid2FaSync() =>
    RustLib.instance.api.crateFlutterFfiMainHasValid2FaSync();

Future<String> mainVerifyBot({required String token}) =>
    RustLib.instance.api.crateFlutterFfiMainVerifyBot(token: token);

bool mainHasValidBotSync() =>
    RustLib.instance.api.crateFlutterFfiMainHasValidBotSync();

String mainGetHardOption({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetHardOption(key: key);

String mainGetBuildinOption({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetBuildinOption(key: key);

Future<void> mainCheckHwcodec() =>
    RustLib.instance.api.crateFlutterFfiMainCheckHwcodec();

Future<String> mainGetTrustedDevices() =>
    RustLib.instance.api.crateFlutterFfiMainGetTrustedDevices();

Future<void> mainRemoveTrustedDevices({required String json}) =>
    RustLib.instance.api.crateFlutterFfiMainRemoveTrustedDevices(json: json);

Future<void> mainClearTrustedDevices() =>
    RustLib.instance.api.crateFlutterFfiMainClearTrustedDevices();

int mainMaxEncryptLen() =>
    RustLib.instance.api.crateFlutterFfiMainMaxEncryptLen();

Future<void> sessionRequestNewDisplayInitMsgs({
  required UuidValue sessionId,
  required int display,
}) => RustLib.instance.api.crateFlutterFfiSessionRequestNewDisplayInitMsgs(
  sessionId: sessionId,
  display: display,
);

bool mainAudioSupportLoopback() =>
    RustLib.instance.api.crateFlutterFfiMainAudioSupportLoopback();

String mainGetPrinterNames() =>
    RustLib.instance.api.crateFlutterFfiMainGetPrinterNames();

Future<String> mainGetCommon({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetCommon(key: key);

String mainGetCommonSync({required String key}) =>
    RustLib.instance.api.crateFlutterFfiMainGetCommonSync(key: key);

Future<void> mainSetCommon({required String key, required String value}) =>
    RustLib.instance.api.crateFlutterFfiMainSetCommon(key: key, value: value);

Future<void> sessionSetCommon({
  required UuidValue sessionId,
  required String key,
  required String value,
}) => RustLib.instance.api.crateFlutterFfiSessionSetCommon(
  sessionId: sessionId,
  key: key,
  value: value,
);

String? sessionGetCommonSync({
  required UuidValue sessionId,
  required String key,
  required String param,
}) => RustLib.instance.api.crateFlutterFfiSessionGetCommonSync(
  sessionId: sessionId,
  key: key,
  param: param,
);

Future<String?> sessionGetCommon({
  required UuidValue sessionId,
  required String key,
  required String param,
}) => RustLib.instance.api.crateFlutterFfiSessionGetCommon(
  sessionId: sessionId,
  key: key,
  param: param,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ResultType < () >>>
abstract class ResultType implements RustOpaqueInterface {}

@freezed
sealed class EventToUI with _$EventToUI {
  const EventToUI._();

  const factory EventToUI.event(String field0) = EventToUI_Event;
  const factory EventToUI.rgba(int field0) = EventToUI_Rgba;
  const factory EventToUI.texture(int field0, bool field1) = EventToUI_Texture;
}
