[package]
name = "virtual_display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen = "0.1"
lazy_static = "1.4"
camellia_remote_protocol = { package = "camellia-remote-protocol", path = "../camellia_remote_protocol" }
